[tool.poetry]
name = "gemini"
version = "0.9.2"
description = "Python API for GEMINI framework"
authors = ["Pranav Ghate <pranavghate94@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "3.0.2"
minio = "7.2.4"
pydantic = "2.9.2"
python-dotenv = "1.0.1"
tqdm = "4.66.4"
rich = "13.7.1"
setuptools = "74.1.2"
SQLAlchemy = "2.0.26"
psycopg2-binary = "2.9.9"
waitress = "2.1.0"
requests = "2.31.0"
pandas = "2.2.2"
dask = {extras = ["dataframe"], version = "2024.4.0"}
sqlalchemy-mixins = "*"
cachetools = "5.3.3"
openpyxl = "3.1.2"
litestar = "2.8.3"
farm-ng-core = "2.3.1"
farm-ng-amiga = "2.3.2"
kornia = "0.7.3"
scipy = "1.14.1"
opencv-python = "4.10.0.84"
prefect = "3.0.11"
docker = "7.1.0"
click = "8.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gemini = "gemini.cli:main"