[tool.poetry]
name = "gemini-framework"
version = "0.9.6"
description = "GEMINI Framework"
authors = ["Pranav Ghate <pghate@ucdavis.edu>"]
readme = "README.md"
packages = [
    { include = "gemini"}
]

[tool.poetry.dependencies]
python = "^3.10"
minio = "7.2.4"
python-on-whales = "0.73.0"
redis = "5.2.0"
sqlalchemy = "2.0.26"
sqlalchemy-mixins = "2.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
