version: "3"

vars:
  ENV_FILE: .env

tasks:



  # Docker tasks
  start-containers:
    cmds:
      - docker compose --env-file {{.ENV_FILE}} up -d --build

  stop-containers:
    cmds:
      - docker compose --env-file {{.ENV_FILE}} down

  clean-containers:
    cmds:
      - docker compose --env-file {{.ENV_FILE}} down --volumes --remove-orphans

  reset-containers:
    cmds:
      - task clean-containers
      - task start-containers

  prune-containers:
    cmds:
      - docker system prune -f

  purge-containers:
    cmds:
      - task clean-containers
      - docker system prune -fa

  # Main tasks
  start:
    cmds:
      - task start-containers
   
  stop:
    cmds:
      - task stop-containers

  reset:
    cmds:
      - task reset-containers

  clean:
    cmds:
      - task clean-containers
    
 