version: "3"

vars:
  ENV_FILE: .env.example

# Load environment variables from .env file
dotenv: ["{{.ENV_FILE}}"]

tasks:

  # Docker tasks
  start-containers:
    cmds:
      - docker-compose --env-file {{.ENV_FILE}} up -d --build

  stop-containers:
    cmds:
      - docker-compose --env-file {{.ENV_FILE}} down

  clean-containers:
    cmds:
      - docker-compose --env-file {{.ENV_FILE}} down --volumes --remove-orphans

  reset-containers:
    cmds:
      - task clean-containers
      - task start-containers

  prune-containers:
    cmds:
      - docker system prune -f

  purge-containers:
    cmds:
      - task clean-containers
      - docker system prune -fa

  # Main Pipeline Tasks
  install:
    cmds:
      - pip install -e .

  start:
    cmds:
      - task reset-containers
      - task install

  clean:
    deps: [clean-containers]


 