@baseUrl = http://localhost:8000
@apiUrl = {{baseUrl}}/api/cultivars

### Get all the cultivars
# @name GetAllCultivars
GET {{apiUrl}}/all

### Get a specific cultivar
# @name GetCultivar
GET {{apiUrl}}/?experiment_name=Experiment+A

### Select a cultivar
@cultivarId = {{GetCultivar.response.body.$.0.id}}

### Select a cultivar by ID
# @name GetCultivarById
GET {{apiUrl}}/id/{{cultivarId}}

### Get all associated experiments by cultivar ID
# @name GetExperimentsByCultivarId
GET {{apiUrl}}/id/{{cultivarId}}/experiments

### Get all associated plots by cultivar ID
# @name GetPlotsByCultivarId
GET {{apiUrl}}/id/{{cultivarId}}/plots

### Get all associated plants by cultivar ID
# @name GetPlantsByCultivarId
GET {{apiUrl}}/id/{{cultivarId}}/plants

### Create a new cultivar
# @name CreateCultivar
POST {{apiUrl}}
Content-Type: application/json

{
    "cultivar_accession": "Test Accession Z",
    "cultivar_population": "Test Population Z",
    "cultivar_info": {
        "cultivar_name": "Test Cultivar Z",
        "cultivar_description": "Test Description Z",
        "cultivar_origin": "Test Origin Z",
        "cultivar_usage": "Test Usage Z",
        "cultivar_notes": "Test Notes Z"
    },
    "experiment_name": "Experiment B"
}

###
@createdCultivarId = {{CreateCultivar.response.body.id}}

### Update a cultivar
# @name UpdateCultivar
PATCH {{apiUrl}}/id/{{createdCultivarId}}
Content-Type: application/json

{
    "cultivar_accession": "Updated Accession Z",
    "cultivar_population": "Updated Population Z",
    "cultivar_info": {
        "cultivar_name": "Updated Cultivar Z",
        "cultivar_description": "Updated Description Z",
        "cultivar_origin": "Updated Origin Z",
        "cultivar_usage": "Updated Usage Z",
        "cultivar_notes": "Updated Notes Z"
    },
    "experiment_name": "Experiment B"
}

### Delete a cultivar
# @name DeleteCultivar
DELETE {{apiUrl}}/id/{{createdCultivarId}}
