@baseUrl = http://localhost:8000
@apiUrl = {{baseUrl}}/api/plants

### Get all plants
# @name GetAllPlants
GET {{apiUrl}}/all

### Get a specific plant
# @name GetPlant
GET {{apiUrl}}/?experiment_name=Experiment+A

### Select a plant
@plantId = {{GetPlant.response.body.$.0.id}}

### Select a plant by ID
# @name GetPlantById
GET {{apiUrl}}/id/{{plantId}}

### Get all associated plots by plant ID
# @name GetPlotsByPlantId
GET {{apiUrl}}/id/{{plantId}}/plot

### Get associated cultivar by plant ID
# @name GetCultivarByPlantId
GET {{apiUrl}}/id/{{plantId}}/cultivar

### Create a new plant
# @name CreatePlant
POST {{apiUrl}}
Content-Type: application/json

{
    "plant_number": 666,
    "plant_info": {
        "plant_description": "Test Description",
        "plant_notes": "Test Notes"
    },
    "cultivar_accession": "Accession A1",
    "cultivar_population": "Population A",
    "experiment_name": "Experiment A",
    "season_name": "Season 1A",
    "site_name": "Site A1",
    "plot_number": 1,
    "plot_row_number": 1,
    "plot_column_number": 1
}

###
@createdPlantId = {{CreatePlant.response.body.id}}

### Update a plant
# @name UpdatePlant
PATCH {{apiUrl}}/id/{{createdPlantId}}
Content-Type: application/json

{
    "plant_number": 666,
    "plant_info": {
        "plant_description": "Updated Description",
        "plant_notes": "Updated Notes"
    }
}

### Delete a plant
# @name DeletePlant
DELETE {{apiUrl}}/id/{{createdPlantId}}
