@baseUrl = http://localhost:8000
@apiUrl = http://localhost:8000/api

// ---- Check the API status ----
GET {{baseUrl}}

// ----------------------
// ---- Cultivar API ----
// ----------------------

### Get all cultivars
# @name list_cultivars
GET {{apiUrl}}/cultivars

### Select a cultivar
@cultivarId = {{list_cultivars.response.body.$.0.id}}

### Create a new cultivar
# @name create_cultivar
POST {{apiUrl}}/cultivars
Content-Type: application/json

{
    "cultivar_accession": "Test Accession Z",
    "cultivar_population": "Test Population Z",
    "cultivar_info": {
        "cultivar_name": "Test Cultivar Z",
        "cultivar_description": "Test Description Z",
        "cultivar_origin": "Test Origin Z",
        "cultivar_usage": "Test Usage Z",
        "cultivar_notes": "Test Notes Z"
    },
    "experiment_name": "Experiment B"
}

###
@createdCultivarId = {{create_cultivar.response.body.id}}

### Get a cultivar by ID
# @name get_cultivar_by_id
GET {{apiUrl}}/cultivars/id/{{createdCultivarId}}

### Update a cultivar
# @name update_cultivar
PATCH  {{apiUrl}}/cultivars/id/{{createdCultivarId}}
Content-Type: application/json

{
    "cultivar_accession": "Test Accession ZA",
    "cultivar_population": "Test Population ZA",
    "cultivar_info": {
        "cultivar_name": "Test Cultivar ZA",
        "cultivar_description": "Test Description ZA",
        "cultivar_origin": "Test Origin ZA",
        "cultivar_usage": "Test Usage ZA",
        "cultivar_notes": "Test Notes ZA"
    }
}

### Delete a cultivar
# @name delete_cultivar
DELETE {{apiUrl}}/cultivars/id/{{createdCultivarId}}

### Get Population Accessions
# @name get_population_accessions
@population = Population A

GET {{apiUrl}}/cultivars/accessions/{{population}}

// -------------------------
// ---- Data Format API ----
// -------------------------

### List all data formats
# @name list_data_formats
@data_format_name = JSON
GET {{apiUrl}}/data_formats?data_format_name={{data_format_name}}

### Create a new data format
# @name create_data_format
POST {{apiUrl}}/data_formats
Content-Type: application/json

{
    "data_format_name": "Test Data Format",
    "data_format_mime_type": "application/test",
    "data_format_info": {
        "data_format_description": "Test Description",
        "data_format_extension": "Test Extension",
        "data_format_mime_type": "Test MIME Type",
        "data_format_notes": "Test Notes"
    }
}

###
@createdDataFormatId = {{create_data_format.response.body.id}}

### Get a data format by ID
# @name get_data_format_by_id
GET {{apiUrl}}/data_formats/id/{{createdDataFormatId}}

### Update a data format
# @name update_data_format
PATCH  {{apiUrl}}/data_formats/id/{{createdDataFormatId}}
Content-Type: application/json

{
    "data_format_name": "Test Data Format A",
    "data_format_mime_type": "application/jsonpu+a",
    "data_format_info": {
        "data_format_description": "Test Description A",
        "data_format_extension": "Test Extension A",
        "data_format_mime_type": "Test MIME Type A",
        "data_format_notes": "Test Notes A"
    }
}

### Delete a data format
# @name delete_data_format
DELETE {{apiUrl}}/data_formats/id/{{createdDataFormatId}}


// -----------------------
// ---- Data Type API ----
// -----------------------

### List all data types
# @name list_data_types
@data_type_name = Image
GET {{apiUrl}}/data_types?data_type_name={{data_type_name}}

###
@dataTypeId = {{list_data_types.response.body.$.0.id}}

### Create a new data type
# @name create_data_type
POST {{apiUrl}}/data_types
Content-Type: application/json

{
    "data_type_name": "Test Data Type",
    "data_type_info": {
        "data_type_description": "Test Description",
        "data_type_notes": "Test Notes"
    }
}

###
@createdDataTypeId = {{create_data_type.response.body.id}}

### Get a data type by ID
# @name get_data_type_by_id
GET {{apiUrl}}/data_types/id/{{createdDataTypeId}}

### Update a data type
# @name update_data_type
PATCH  {{apiUrl}}/data_types/id/{{createdDataTypeId}}
Content-Type: application/json

{
    "data_type_name": "Test Data Type A",
    "data_type_info": {
        "data_type_description": "Test Description A",
        "data_type_notes": "Test Notes A"
    }
}

### Delete a data type
# @name delete_data_type
DELETE {{apiUrl}}/data_types/id/{{createdDataTypeId}}

### Get Data Type Formats
# @name get_data_type_formats
GET {{apiUrl}}/data_types/id/{{dataTypeId}}/formats

### Create a new data type format
# @name create_data_type_format
POST {{apiUrl}}/data_types/id/{{dataTypeId}}/formats
Content-Type: application/json

{
    "data_format_name": "Test Data Format",
    "data_format_mime_type": "application/test",
    "data_type_format_info": {
        "data_type_format_description": "Test Description",
        "data_type_format_notes": "Test Notes"
    }
}


// --------------------------
// ---- Dataset Type API ----
// --------------------------

### List all dataset types
# @name list_dataset_types
@dataset_type_name = Sensor
GET {{apiUrl}}/dataset_types?dataset_type_name={{dataset_type_name}}

### Create a new dataset type
# @name create_dataset_type
POST {{apiUrl}}/dataset_types
Content-Type: application/json

{
    "dataset_type_name": "Test Dataset Type",
    "dataset_type_info": {
        "dataset_type_description": "Test Description",
        "dataset_type_notes": "Test Notes"
    }
}

###
@createdDatasetTypeId = {{create_dataset_type.response.body.id}}

### Get a dataset type by ID
# @name get_dataset_type_by_id
GET {{apiUrl}}/dataset_types/id/{{createdDatasetTypeId}}

### Update a dataset type
# @name update_dataset_type
PATCH  {{apiUrl}}/dataset_types/id/{{createdDatasetTypeId}}
Content-Type: application/json

{
    "dataset_type_name": "Test Dataset Type A",
    "dataset_type_info": {
        "dataset_type_description": "Test Description A",
        "dataset_type_notes": "Test Notes A"
    }
}

### Delete a dataset type
# @name delete_dataset_type
DELETE {{apiUrl}}/dataset_types/id/{{createdDatasetTypeId}}

// ----------------------
// ---- Dataset API -----
// ----------------------

### List all datasets
# @name list_datasets
GET {{apiUrl}}/datasets

###
@datasetId = {{list_datasets.response.body.$.0.id}}

### Create a new dataset
# @name create_dataset
POST {{apiUrl}}/datasets
Content-Type: application/json

{
    "dataset_name": "Test Dataset",
    "dataset_type_id": 1,
    "dataset_info": {
        "dataset_description": "Test Description",
        "dataset_notes": "Test Notes"
    },
    "collection_date": "2021-01-01",
    "experiment_name": "Experiment B"
}

###
@createdDatasetId = {{create_dataset.response.body.id}}

### Get a dataset by ID
# @name get_dataset_by_id
GET {{apiUrl}}/datasets/id/{{createdDatasetId}}

### Update a dataset
# @name update_dataset
PATCH  {{apiUrl}}/datasets/id/{{createdDatasetId}}
Content-Type: application/json

{
    "dataset_name": "Test Dataset A",
    "dataset_type_id": 1,
    "dataset_info": {
        "dataset_description": "Test Description A",
        "dataset_notes": "Test Notes A"
    },
    "collection_date": "2021-01-02"
}

### Delete a dataset
# @name delete_dataset
DELETE {{apiUrl}}/datasets/id/{{createdDatasetId}}

### Search Dataset Data
# @name search_dataset_data
GET {{apiUrl}}/datasets/id/{{datasetId}}/records

### Add a dataset record
# @name add_dataset_record
POST {{apiUrl}}/datasets/id/{{datasetId}}/records
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="timestamp"

2021-01-01T00:00:00Z
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="collection_date"

2021-01-01
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dataset_data"

{"data": "test"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="experiment_name"

Experiment A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="season_name"

Season 1A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="site_name"

Site A1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="record_info"

{"record_description": "Test Description", "record_notes": "Test Notes"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="record_file"; filename="example.txt" Content-Type: text/plain

< ./example.txt

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
@createdDatasetRecordId = {{add_dataset_record.response.body.id}}

### Get a dataset record by ID
# @name get_dataset_record_by_id
GET {{apiUrl}}/datasets/records/id/{{createdDatasetRecordId}}

### Update a dataset record
# @name update_dataset_record
PATCH  {{apiUrl}}/datasets/records/id/{{createdDatasetRecordId}}
Content-Type: application/json

{
    "dataset_data": {"data": "test updated"},
    "record_info": {
        "record_description": "Test Description A",
        "record_notes": "Test Notes A"
    }
}

### Delete a dataset record
# @name delete_dataset_record
DELETE {{apiUrl}}/datasets/records/id/{{createdDatasetRecordId}}


// ------------------------
// ---- Experiment API ----
// ------------------------

### List all experiments
# @name list_experiments
@experiment_name = Experiment A
GET {{apiUrl}}/experiments?experiment_name={{experiment_name}}

### Experiment A ID
@experimentId = {{list_experiments.response.body.$.0.id}}

### Create a new experiment
# @name create_experiment
POST {{apiUrl}}/experiments
Content-Type: application/json

{
    "experiment_name": "Test Experiment Z",
    "experiment_info": {
        "experiment_description": "Test Description",
        "experiment_notes": "Test Notes"
    },
    "experiment_start_date": "2021-01-01",
    "experiment_end_date": "2021-12-31"
}

###
@createdExperimentId = {{create_experiment.response.body.id}}

### Get an experiment by ID
# @name get_experiment_by_id
GET {{apiUrl}}/experiments/id/{{createdExperimentId}}

### Update an experiment
# @name update_experiment
PATCH  {{apiUrl}}/experiments/id/{{createdExperimentId}}
Content-Type: application/json

{
    "experiment_name": "Test Experiment ZA",
    "experiment_info": {
        "experiment_description": "Test Description A",
        "experiment_notes": "Test Notes A"
    },
    "experiment_start_date": "2021-01-02",
    "experiment_end_date": "2021-12-30"
}

### Delete an experiment
# @name delete_experiment
DELETE {{apiUrl}}/experiments/id/{{createdExperimentId}}

### Get Experiment Seasons
# @name get_experiment_seasons
GET {{apiUrl}}/experiments/id/{{experimentId}}/seasons

### Create Season for Experiment
# @name create_experiment_season
POST {{apiUrl}}/experiments/id/{{experimentId}}/seasons
Content-Type: application/json

{
    "season_name": "Test Season X",
    "season_info": {
        "season_description": "Test Description",
        "season_notes": "Test Notes"
    },
    "season_start_date": "2021-01-01",
    "season_end_date": "2021-12-31"
}


### Get Experiment Sites
# @name get_experiment_sites
GET {{apiUrl}}/experiments/id/{{experimentId}}/sites

### Create Site for Experiment
# @name create_experiment_site
POST {{apiUrl}}/experiments/id/{{experimentId}}/sites
Content-Type: application/json

{
    "site_name": "Test Site X",
    "site_city": "Test City X",
    "site_state": "Test State X",
    "site_country": "Test Country X",
    "site_info": {
        "site_description": "Test Description",
        "site_notes": "Test Notes"
    }
}

### Get Experiment Cultivars
# @name get_experiment_cultivars
GET {{apiUrl}}/experiments/id/{{experimentId}}/cultivars

### Create Cultivar for Experiment
# @name create_experiment_cultivar
POST {{apiUrl}}/experiments/id/{{experimentId}}/cultivars
Content-Type: application/json

{
    "cultivar_accession": "Test Accession X",
    "cultivar_population": "Test Population X",
    "cultivar_info": {
        "cultivar_name": "Test Cultivar X",
        "cultivar_description": "Test Description X",
        "cultivar_origin": "Test Origin X",
        "cultivar_usage": "Test Usage X",
        "cultivar_notes": "Test Notes X"
    }
}

### Get Experiment Sensor Platforms
# @name get_experiment_sensor_platforms
GET {{apiUrl}}/experiments/id/{{experimentId}}/sensor_platforms

### Create Sensor Platform for Experiment
# @name create_experiment_sensor_platform
POST {{apiUrl}}/experiments/id/{{experimentId}}/sensor_platforms
Content-Type: application/json

{
    "sensor_platform_name": "Test Sensor Platform X",
    "sensor_platform_info": {
        "sensor_platform_description": "Test Description",
        "sensor_platform_notes": "Test Notes"
    }
}

### Get Experiment Sensors
# @name get_experiment_sensors
GET {{apiUrl}}/experiments/id/{{experimentId}}/sensors

### Create Sensor for Experiment
# @name create_experiment_sensor
POST {{apiUrl}}/experiments/id/{{experimentId}}/sensors
Content-Type: application/json

{
    "sensor_name": "Test Sensor X",
    "sensor_info": {
        "sensor_description": "Test Description",
        "sensor_notes": "Test Notes"
    },
    "sensor_type_id": 1,
    "sensor_data_format_id": 1,
    "sensor_data_type_id": 1
}

### Get Experiment Traits
# @name get_experiment_traits
GET {{apiUrl}}/experiments/id/{{experimentId}}/traits

### Create Trait for Experiment
# @name create_experiment_trait
POST {{apiUrl}}/experiments/id/{{experimentId}}/traits
Content-Type: application/json

{
    "trait_name": "Test Trait X",
    "trait_info": {
        "trait_description": "Test Description",
        "trait_notes": "Test Notes"
    },
    "trait_level_id": 1,
    "trait_metrics": {
        "trait_metric_name": "Test Metric X",
        "trait_metric_description": "Test Description X",
        "trait_metric_notes": "Test Notes X"
    },
    "trait_units": "Test Units X"
}

### Get Experiment Scripts
# @name get_experiment_scripts
GET {{apiUrl}}/experiments/id/{{experimentId}}/scripts

### Create Script for Experiment
# @name create_experiment_script
POST {{apiUrl}}/experiments/id/{{experimentId}}/scripts
Content-Type: application/json

{
    "script_name": "Test Script X",
    "script_url": "http://test.com",
    "script_info": {
        "script_description": "Test Description",
        "script_notes": "Test Notes"
    }
}

### Get Experiment Procedures
# @name get_experiment_procedures
GET {{apiUrl}}/experiments/id/{{experimentId}}/procedures

### Create Procedure for Experiment
# @name create_experiment_procedure
POST {{apiUrl}}/experiments/id/{{experimentId}}/procedures
Content-Type: application/json

{
    "procedure_name": "Test Procedure X",
    "procedure_info": {
        "procedure_description": "Test Description",
        "procedure_notes": "Test Notes"
    }
}

### Get Experiment Models
# @name get_experiment_models
GET {{apiUrl}}/experiments/id/{{experimentId}}/models

### Create Model for Experiment
# @name create_experiment_model
POST {{apiUrl}}/experiments/id/{{experimentId}}/models
Content-Type: application/json

{
    "model_name": "Test Model X",
    "model_url": "http://test.com",
    "model_info": {
        "model_description": "Test Description",
        "model_notes": "Test Notes"
    }
}

### Get Experiment Datasets
# @name get_experiment_datasets
GET {{apiUrl}}/experiments/id/{{experimentId}}/datasets

### Create Dataset for Experiment
# @name create_experiment_dataset
POST {{apiUrl}}/experiments/id/{{experimentId}}/datasets
Content-Type: application/json

{
    "dataset_name": "Test Dataset X",
    "dataset_type_id": 1,
    "dataset_info": {
        "dataset_description": "Test Description",
        "dataset_notes": "Test Notes"
    },
    "collection_date": "2021-01-01"
}

// ----------------------
// ---- Season API ------
// ----------------------

### List all seasons
# @name list_seasons
@experiment_name = Experiment A
GET {{apiUrl}}/seasons?experiment_name={{experiment_name}}

### Select a season
@seasonId = {{list_seasons.response.body.$.0.id}}

### Create a new season
# @name create_season
POST {{apiUrl}}/seasons
Content-Type: application/json

{
    "season_name": "Test Season Z",
    "season_info": {
        "season_description": "Test Description",
        "season_notes": "Test Notes"
    },
    "season_start_date": "2021-01-01",
    "season_end_date": "2021-12-31",
    "experiment_name": "Experiment A"
}

###
@createdSeasonId = {{create_season.response.body.id}}

### Get a season by ID
# @name get_season_by_id
GET {{apiUrl}}/seasons/id/{{createdSeasonId}}

### Update a season
# @name update_season
PATCH  {{apiUrl}}/seasons/id/{{createdSeasonId}}
Content-Type: application/json

{
    "season_name": "Test Season ZA",
    "season_info": {
        "season_description": "Test Description A",
        "season_notes": "Test Notes A"
    },
    "season_start_date": "2021-01-02",
    "season_end_date": "2021-12-30"
}

### Delete a season
# @name delete_season
DELETE {{apiUrl}}/seasons/id/{{createdSeasonId}}

// ----------------------
// ---- Site API --------
// ----------------------

### List all sites
# @name list_sites
@experiment_name = Experiment A
GET {{apiUrl}}/sites?experiment_name={{experiment_name}}

### Select a site
@siteId = {{list_sites.response.body.$.0.id}}

### Create a new site
# @name create_site
POST {{apiUrl}}/sites
Content-Type: application/json

{
    "site_name": "Test Site Z",
    "site_city": "Test City Z",
    "site_state": "Test State Z",
    "site_country": "Test Country Z",
    "site_info": {
        "site_description": "Test Description",
        "site_notes": "Test Notes"
    },
    "experiment_name": "Experiment A"
}

###
@createdSiteId = {{create_site.response.body.id}}

### Get a site by ID
# @name get_site_by_id
GET {{apiUrl}}/sites/id/{{createdSiteId}}

### Update a site
# @name update_site
PATCH  {{apiUrl}}/sites/id/{{createdSiteId}}
Content-Type: application/json

{
    "site_name": "Test Site ZA",
    "site_city": "Test City ZA",
    "site_state": "Test State ZA",
    "site_country": "Test Country ZA",
    "site_info": {
        "site_description": "Test Description A",
        "site_notes": "Test Notes A"
    }
}

### Delete a site
# @name delete_site
DELETE {{apiUrl}}/sites/id/{{createdSiteId}}

// ----------------------
// ---- Plot API --------
// ----------------------

### List all plots
# @name list_plots
@experiment_name = Experiment A
@season_name = Season 1A
@site_name = Site A1
GET {{apiUrl}}/plots?experiment_name={{experiment_name}}&season_name={{season_name}}&site_name={{site_name}}

### Select a plot
@plotId = {{list_plots.response.body.$.0.id}}

### Create a new plot
# @name create_plot
POST {{apiUrl}}/plots
Content-Type: application/json

{
    "plot_number" : 9900,
    "plot_row_number" : 9900,
    "plot_column_number" : 9900,
    "plot_info": {
        "plot_description": "Test Description",
        "plot_notes": "Test Notes"
    },
    "experiment_name": "Experiment A",
    "season_name": "Season 1A",
    "site_name": "Site A1"
}

###
@createdPlotId = {{create_plot.response.body.id}}

### Get a plot by ID
# @name get_plot_by_id
GET {{apiUrl}}/plots/id/{{createdPlotId}}

### Update a plot
# @name update_plot
PATCH  {{apiUrl}}/plots/id/{{createdPlotId}}
Content-Type: application/json

{
    "plot_number" : 9901,
    "plot_row_number" : 9901,
    "plot_column_number" : 9901,
    "plot_info": {
        "plot_description": "Test Description A",
        "plot_notes": "Test Notes A"
    }
}

### Delete a plot
# @name delete_plot
DELETE {{apiUrl}}/plots/id/{{createdPlotId}}

### Get Plot Cultivars
# @name get_plot_cultivars
GET {{apiUrl}}/plots/id/{{plotId}}/cultivars

### Get Plot Plants
# @name get_plot_plants
GET {{apiUrl}}/plots/id/{{plotId}}/plants

// ----------------------
// ---- Plant API -------
// ----------------------

### List all plants
# @name list_plants
GET {{apiUrl}}/plants?plot_id={{plotId}}

### Create a new plant
# @name create_plant
POST {{apiUrl}}/plants
Content-Type: application/json

{
    "plot_id": "{{plotId}}",
    "plant_number": 9900,
    "plant_info": {
        "plant_description": "Test Description",
        "plant_notes": "Test Notes"
    },
    "cultivar_accession": "Accession A1",
    "cultivar_population": "Population A"
}

### 
@createdPlantId = {{create_plant.response.body.id}}

### Update a plant
# @name update_plant
PATCH  {{apiUrl}}/plants/id/{{createdPlantId}}
Content-Type: application/json

{
    "plant_number": 9901,
    "plant_info": {
        "plant_description": "Test Description A",
        "plant_notes": "Test Notes A"
    }
}

### Get a plant by ID
# @name get_plant_by_id
GET {{apiUrl}}/plants/id/{{createdPlantId}}

### Get Plant Cultivar
# @name get_plant_cultivar
GET {{apiUrl}}/plants/id/{{createdPlantId}}/cultivar

### Set Plant Cultivar
# @name set_plant_cultivar
POST  {{apiUrl}}/plants/id/{{createdPlantId}}/cultivar
Content-Type: application/json

{
    "cultivar_accession": "Accession A2",
    "cultivar_population": "Population A"
}

### Delete a plant
# @name delete_plant
DELETE {{apiUrl}}/plants/id/{{createdPlantId}}

// ----------------------
// ---- Procedure API ---
// ----------------------

### List all procedures
# @name list_procedures
GET {{apiUrl}}/procedures

###
@procedureId = {{list_procedures.response.body.$.0.id}}

### Create a new procedure
# @name create_procedure
POST {{apiUrl}}/procedures
Content-Type: application/json

{
    "procedure_name": "Test Procedure",
    "procedure_info": {
        "procedure_description": "Test Description",
        "procedure_notes": "Test Notes"
    },
    "experiment_name": "Experiment B"
}

###
@createdProcedureId = {{create_procedure.response.body.id}}

### Get a procedure by ID
# @name get_procedure_by_id
GET {{apiUrl}}/procedures/id/{{createdProcedureId}}

### Update a procedure
# @name update_procedure
PATCH  {{apiUrl}}/procedures/id/{{createdProcedureId}}
Content-Type: application/json

{
    "procedure_name": "Test Procedure A",
    "procedure_info": {
        "procedure_description": "Test Description A",
        "procedure_notes": "Test Notes A"
    }
}

### Delete a procedure
# @name delete_procedure
DELETE {{apiUrl}}/procedures/id/{{createdProcedureId}}

### Get Procedure Runs
# @name get_procedure_runs
GET {{apiUrl}}/procedures/id/{{procedureId}}/runs

### Create a new procedure run
# @name create_procedure_run
POST {{apiUrl}}/procedures/id/{{procedureId}}/runs
Content-Type: application/json

{
    "procedure_run_info": {
        "procedure_run_description": "Test Description",
        "procedure_run_notes": "Test Notes"
    }
}

### Get Procedure Datasets
# @name get_procedure_datasets
GET {{apiUrl}}/procedures/id/{{procedureId}}/datasets

### Create a new procedure dataset
# @name create_procedure_dataset
POST {{apiUrl}}/procedures/id/{{procedureId}}/datasets
Content-Type: application/json

{
    "dataset_name": "Test Procedure Dataset",
    "dataset_info": {
        "dataset_description": "Test Description",
        "dataset_notes": "Test Notes"
    },
    "collection_date": "2021-01-01",
    "experiment_name": "Experiment B"
}

### Search Procedure Data
# @name search_procedure_data
GET {{apiUrl}}/procedures/id/{{procedureId}}/records

// ----------------------
// ---- Model API -------
// ----------------------

### List all models
# @name list_models
GET {{apiUrl}}/models

###
@modelId = {{list_models.response.body.$.0.id}}

### Create a new model
# @name create_model
POST {{apiUrl}}/models
Content-Type: application/json

{
    "model_name": "Test Model",
    "model_url": "http://test.com",
    "model_info": {
        "model_description": "Test Description",
        "model_notes": "Test Notes"
    },
    "experiment_name": "Experiment B"
}

###
@createdModelId = {{create_model.response.body.id}}

### Get a model by ID
GET {{apiUrl}}/models/id/{{createdModelId}}

### Update a model
# @name update_model
PATCH  {{apiUrl}}/models/id/{{createdModelId}}
Content-Type: application/json

{
    "model_name": "Test Model A",
    "model_url": "http://test.com/a",
    "model_info": {
        "model_description": "Test Description A",
        "model_notes": "Test Notes A"
    }
}

### Delete a model
# @name delete_model
DELETE {{apiUrl}}/models/id/{{createdModelId}}

### Get Model Runs
# @name get_model_runs
GET {{apiUrl}}/models/id/{{modelId}}/runs

### Create a new model run
# @name create_model_run
POST {{apiUrl}}/models/id/{{modelId}}/runs
Content-Type: application/json

{
    "model_run_info": {
        "model_run_description": "Test Description",
        "model_run_notes": "Test Notes"
    }
}

### Get Model Datasets
# @name get_model_datasets
GET {{apiUrl}}/models/id/{{modelId}}/datasets

### Create a new model dataset
# @name create_model_dataset
POST {{apiUrl}}/models/id/{{modelId}}/datasets
Content-Type: application/json

{
    "dataset_name": "Test Model Dataset",
    "dataset_info": {
        "dataset_description": "Test Description",
        "dataset_notes": "Test Notes"
    },
    "collection_date": "2021-01-01",
    "experiment_name": "Experiment B"
}

### Search Model Data
# @name search_model_data
GET {{apiUrl}}/models/id/{{modelId}}/records

### Add a model record
# @name add_model_record
POST {{apiUrl}}/models/id/{{modelId}}/records
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="timestamp"

2021-01-01T00:00:00Z
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="model_data"

{"data": "test"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="experiment_name"

Experiment A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="season_name"

Season 1A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="site_name"

Site A1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="record_file"; filename="example.txt" Content-Type: text/plain

< ./example.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="record_info"

{"record_description": "Test Description", "record_notes": "Test Notes"}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
@createdModelRecordId = {{add_model_record.response.body.id}}

### Get a model record by ID
# @name get_model_record_by_id
GET {{apiUrl}}/models/records/id/{{createdModelRecordId}}

### Update a model record
# @name update_model_record
PATCH  {{apiUrl}}/models/records/id/{{createdModelRecordId}}
Content-Type: application/json

{
    "model_data": {"data": "test updated"},
    "record_info": {
        "record_description": "Test Description A",
        "record_notes": "Test Notes A"
    }
}

### Delete a model record
# @name delete_model_record
DELETE {{apiUrl}}/models/records/id/{{createdModelRecordId}}

// ----------------------
// ---- Script API ------
// ----------------------

### List all scripts
# @name list_scripts
GET {{apiUrl}}/scripts

###
@scriptId = {{list_scripts.response.body.$.0.id}}

### Create a new script
# @name create_script
POST {{apiUrl}}/scripts
Content-Type: application/json

{
    "script_name": "Test Script",
    "script_url": "http://test.com",
    "script_info": {
        "script_description": "Test Description",
        "script_notes": "Test Notes"
    },
    "experiment_name": "Experiment B"
}

###
@createdScriptId = {{create_script.response.body.id}}

### Get a script by ID
GET {{apiUrl}}/scripts/id/{{createdScriptId}}

### Update a script
# @name update_script
PATCH  {{apiUrl}}/scripts/id/{{createdScriptId}}
Content-Type: application/json

{
    "script_name": "Test Script A",
    "script_url": "http://test.com/a",
    "script_info": {
        "script_description": "Test Description A",
        "script_notes": "Test Notes A"
    }
}

### Delete a script
# @name delete_script
DELETE {{apiUrl}}/scripts/id/{{createdScriptId}}

### Get Script Runs
# @name get_script_runs
GET {{apiUrl}}/scripts/id/{{scriptId}}/runs

### Create a new script run
# @name create_script_run
POST {{apiUrl}}/scripts/id/{{scriptId}}/runs
Content-Type: application/json

{
    "script_run_info": {
        "script_run_description": "Test Description",
        "script_run_notes": "Test Notes"
    }
}

### Get Script Datasets
# @name get_script_datasets
GET {{apiUrl}}/scripts/id/{{scriptId}}/datasets

### Create a new script dataset
# @name create_script_dataset
POST {{apiUrl}}/scripts/id/{{scriptId}}/datasets

{
    "dataset_name": "Test Script Dataset",
    "dataset_info": {
        "dataset_description": "Test Description",
        "dataset_notes": "Test Notes"
    },
    "collection_date": "2021-01-01",
    "experiment_name": "Experiment B"
}

### Search Script Data
# @name search_script_data
GET {{apiUrl}}/scripts/id/{{scriptId}}/records

### Add a script record
# @name add_script_record
POST {{apiUrl}}/scripts/id/{{scriptId}}/records
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="timestamp"

2021-01-01T00:00:00Z
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="script_data"

{"data": "test"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="experiment_name"

Experiment A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="season_name"

Season 1A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="site_name"

Site A1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="record_file"; filename="example.txt" Content-Type: text/plain

< ./example.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="record_info"

{"record_description": "Test Description", "record_notes": "Test Notes"}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
@createdScriptRecordId = {{add_script_record.response.body.id}}

### Get a script record by ID
# @name get_script_record_by_id
GET {{apiUrl}}/scripts/records/id/{{createdScriptRecordId}}

### Update a script record
# @name update_script_record
PATCH  {{apiUrl}}/scripts/records/id/{{createdScriptRecordId}}
Content-Type: application/json

{
    "script_data": {"data": "test updated"},
    "record_info": {
        "record_description": "Test Description A",
        "record_notes": "Test Notes A"
    }
}

### Delete a script record
# @name delete_script_record
DELETE {{apiUrl}}/scripts/records/id/{{createdScriptRecordId}}


// -----------------------------
// ---- Sensor Platform API ----
// -----------------------------

### List all sensor platforms
# @name list_sensor_platforms
GET {{apiUrl}}/sensor_platforms

###
@platformId = {{list_sensor_platforms.response.body.$.0.id}}

### Create a new sensor platform
# @name create_sensor_platform
POST {{apiUrl}}/sensor_platforms
Content-Type: application/json

{
    "sensor_platform_name": "Test Sensor Platform",
    "sensor_platform_info": {
        "sensor_platform_description": "Test Description",
        "sensor_platform_notes": "Test Notes"
    },
    "experiment_name": "Experiment B"
}

###
@createdPlatformId = {{create_sensor_platform.response.body.id}}

### Get a sensor platform by ID
# @name get_sensor_platform_by_id
GET {{apiUrl}}/sensor_platforms/id/{{createdPlatformId}}

### Update a sensor platform
# @name update_sensor_platform
PATCH  {{apiUrl}}/sensor_platforms/id/{{createdPlatformId}}
Content-Type: application/json

{
    "sensor_platform_name": "Test Sensor Platform A",
    "sensor_platform_info": {
        "sensor_platform_description": "Test Description A",
        "sensor_platform_notes": "Test Notes A"
    }
}

### Delete a sensor platform
# @name delete_sensor_platform
DELETE {{apiUrl}}/sensor_platforms/id/{{createdPlatformId}}

### Get Sensor Platform Sensors
# @name get_sensor_platform_sensors
GET {{apiUrl}}/sensor_platforms/id/{{platformId}}/sensors

### Create a new sensor platform sensor
# @name create_sensor_platform_sensor
POST {{apiUrl}}/sensor_platforms/id/{{platformId}}/sensors
Content-Type: application/json

{
    "sensor_name": "Test Sensor",
    "sensor_info": {
        "sensor_description": "Test Description",
        "sensor_notes": "Test Notes"
    },
    "sensor_type_id": 1,
    "sensor_data_format_id": 1,
    "sensor_data_type_id": 1,
    "experiment_name": "Experiment B"
}



// -------------------------
// ---- Sensor Type API ----
// -------------------------

### List all sensor types
# @name list_sensor_types
@sensor_type_name=RGB
GET {{apiUrl}}/sensor_types?sensor_type_name={{sensor_type_name}}

###
@sensorTypeId = {{list_sensor_types.response.body.$.0.id}}

### Create a new sensor type
# @name create_sensor_type
POST {{apiUrl}}/sensor_types
Content-Type: application/json

{
    "sensor_type_name": "Test Sensor Type",
    "sensor_type_info": {
        "sensor_type_description": "Test Description",
        "sensor_type_notes": "Test Notes"
    }
}

###
@createdSensorTypeId = {{create_sensor_type.response.body.id}}

### Get a sensor type by ID
# @name get_sensor_type_by_id
GET {{apiUrl}}/sensor_types/id/{{createdSensorTypeId}}

### Update a sensor type
# @name update_sensor_type
PATCH  {{apiUrl}}/sensor_types/id/{{createdSensorTypeId}}
Content-Type: application/json

{
    "sensor_type_name": "Test Sensor Type A",
    "sensor_type_info": {
        "sensor_type_description": "Test Description A",
        "sensor_type_notes": "Test Notes A"
    }
}

### Delete a sensor type
# @name delete_sensor_type
DELETE {{apiUrl}}/sensor_types/id/{{createdSensorTypeId}}

// ----------------------
// ---- Sensor API ------
// ----------------------

### List all sensors
# @name list_sensors
GET {{apiUrl}}/sensors

###
@sensorId = {{list_sensors.response.body.$.0.id}}

### Create a new sensor
# @name create_sensor
POST {{apiUrl}}/sensors
Content-Type: application/json

{
    "sensor_name": "Test Sensor",
    "sensor_info": {
        "sensor_description": "Test Description",
        "sensor_notes": "Test Notes"
    },
    "sensor_type_id": 1,
    "sensor_data_format_id": 1,
    "sensor_data_type_id": 1,
    "experiment_name": "Experiment B"
}

###
@createdSensorId = {{create_sensor.response.body.id}}

### Get a sensor by ID
# @name get_sensor_by_id
GET {{apiUrl}}/sensors/id/{{createdSensorId}}

### Update a sensor
# @name update_sensor
PATCH  {{apiUrl}}/sensors/id/{{createdSensorId}}
Content-Type: application/json

{
    "sensor_name": "Test Sensor A",
    "sensor_info": {
        "sensor_description": "Test Description A",
        "sensor_notes": "Test Notes A"
    },
    "sensor_type_id": 1,
    "sensor_data_format_id": 1,
    "sensor_data_type_id": 1
}

### Delete a sensor
# @name delete_sensor
DELETE {{apiUrl}}/sensors/id/{{createdSensorId}}

### Get Sensor Datasets
# @name get_sensor_datasets
GET {{apiUrl}}/sensors/id/{{sensorId}}/datasets

### Create a new sensor dataset
# @name create_sensor_dataset
POST {{apiUrl}}/sensors/id/{{sensorId}}/datasets
Content-Type: application/json

{
    "dataset_name": "Test Sensor Dataset",
    "dataset_info": {
        "dataset_description": "Test Description",
        "dataset_notes": "Test Notes"
    },
    "collection_date": "2021-01-01",
    "experiment_name": "Experiment B"
}

### Search Sensor Data
# @name search_sensor_data
GET {{apiUrl}}/sensors/id/{{sensorId}}/records

### Create Sensor Record
# @name create_sensor_record
POST {{apiUrl}}/sensors/id/{{sensorId}}/records
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="timestamp"

2021-01-01T00:00:00Z
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="sensor_data"

{"data": "test"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="experiment_name"

Experiment A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="season_name"

Season 1A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="site_name"

Site A1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plot_number"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plot_row_number"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plot_column_number"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="record_file"; filename="example.txt" Content-Type: text/plain

< ./example.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--
Content-Disposition: form-data; name="record_info"

{"record_description": "Test Description", "record_notes": "Test Notes"}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
@createdSensorRecordId = {{create_sensor_record.response.body.id}}

### Get a sensor record by ID
# @name get_sensor_record_by_id
GET {{apiUrl}}/sensors/records/id/{{createdSensorRecordId}}

### Update a sensor record
# @name update_sensor_record
PATCH  {{apiUrl}}/sensors/records/id/{{createdSensorRecordId}}
Content-Type: application/json

{
    "sensor_data": {"data": "test updated"},
    "record_info": {
        "record_description": "Test Description A",
        "record_notes": "Test Notes A"
    }
}

### Delete a sensor record
# @name delete_sensor_record
DELETE {{apiUrl}}/sensors/records/id/{{createdSensorRecordId}}


// -------------------------
// ---- Trait Level API ----
// -------------------------

### List all trait levels
# @name list_trait_levels
@trait_level_name = Plant
GET {{apiUrl}}/trait_levels?trait_level_name={{trait_level_name}}

###
@traitLevelId = {{list_trait_levels.response.body.$.0.id}}

### Create a new trait level
# @name create_trait_level
POST {{apiUrl}}/trait_levels
Content-Type: application/json

{
    "trait_level_name": "Test Trait Level",
    "trait_level_info": {
        "trait_level_description": "Test Description",
        "trait_level_notes": "Test Notes"
    }
}

###
@createdTraitLevelId = {{create_trait_level.response.body.id}}

### Get a trait level by ID
# @name get_trait_level_by_id
GET {{apiUrl}}/trait_levels/id/{{createdTraitLevelId}}

### Update a trait level
# @name update_trait_level
PATCH  {{apiUrl}}/trait_levels/id/{{createdTraitLevelId}}
Content-Type: application/json

{
    "trait_level_name": "Test Trait Level A",
    "trait_level_info": {
        "trait_level_description": "Test Description A",
        "trait_level_notes": "Test Notes A"
    }
}

### Delete a trait level
# @name delete_trait_level
DELETE {{apiUrl}}/trait_levels/id/{{createdTraitLevelId}}

// ----------------------
// ---- Trait API -------
// ----------------------

### List all traits
# @name list_traits
GET {{apiUrl}}/traits

###
@traitId = {{list_traits.response.body.$.0.id}}

### Create a new trait
# @name create_trait
POST {{apiUrl}}/traits
Content-Type: application/json

{
    "trait_name": "Test Trait",
    "trait_info": {
        "trait_description": "Test Description",
        "trait_notes": "Test Notes"
    },
    "trait_level_id": 1,
    "trait_metrics": {
        "trait_metric_name": "Test Metric",
        "trait_metric_description": "Test Description",
        "trait_metric_notes": "Test Notes"
    },
    "trait_units": "Test Units",
    "experiment_name": "Experiment B"
}

###
@createdTraitId = {{create_trait.response.body.id}}

### Get a trait by ID
# @name get_trait_by_id
GET {{apiUrl}}/traits/id/{{createdTraitId}}

### Update a trait
# @name update_trait
PATCH  {{apiUrl}}/traits/id/{{createdTraitId}}
Content-Type: application/json

{
    "trait_name": "Test Trait A",
    "trait_info": {
        "trait_description": "Test Description A",
        "trait_notes": "Test Notes A"
    },
    "trait_level_id": 1,
    "trait_metrics": {
        "trait_metric_name": "Test Metric A",
        "trait_metric_description": "Test Description A",
        "trait_metric_notes": "Test Notes A"
    },
    "trait_units": "Test Units A"
}

### Delete a trait
# @name delete_trait
DELETE {{apiUrl}}/traits/id/{{createdTraitId}}

### Get Trait Datasets
# @name get_trait_datasets
GET {{apiUrl}}/traits/id/{{traitId}}/datasets

### Create a new trait dataset
# @name create_trait_dataset
POST {{apiUrl}}/traits/id/{{traitId}}/datasets
Content-Type: application/json

{
    "dataset_name": "Test Trait Dataset",
    "dataset_info": {
        "dataset_description": "Test Description",
        "dataset_notes": "Test Notes"
    },
    "collection_date": "2021-01-01",
    "experiment_name": "Experiment B"
}

### Search Trait Data
# @name search_trait_data
GET {{apiUrl}}/traits/id/{{traitId}}/records

### Create Trait Record
# @name create_trait_record
POST {{apiUrl}}/traits/id/{{traitId}}/records
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="timestamp"

2021-01-01T00:00:00Z
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="trait_value"

33.456
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="experiment_name"

Experiment A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="season_name"

Season 1A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="site_name"

Site A1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plot_number"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plot_row_number"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plot_column_number"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="record_info"

{"record_description": "Test Description", "record_notes": "Test Notes"}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
@createdTraitRecordId = {{create_trait_record.response.body.id}}

### Get Trait Record by ID
# @name get_trait_record_by_id
GET {{apiUrl}}/traits/records/id/{{createdTraitRecordId}}

### Update Trait Record
# @name update_trait_record
PATCH  {{apiUrl}}/traits/records/id/{{createdTraitRecordId}}
Content-Type: application/json

{
    "trait_value": 33.457,
    "record_info": {
        "record_description": "Test Description A",
        "record_notes": "Test Notes A"
    }
}

### Delete Trait Record
# @name delete_trait_record
DELETE {{apiUrl}}/traits/records/id/{{createdTraitRecordId}}