### GEMINI Rest API
GET http://localhost:5600/api HTTP/1.1

# ---------------------------------------------------------------------------
# Experiments
# ---------------------------------------------------------------------------

### Get All Experiments
GET http://localhost:5600/api/experiments HTTP/1.1

### Get A Specific Experiment (in this case, GEMINI)
GET http://localhost:5600/api/experiments/GEMINI HTTP/1.1

### Create a new Experiment
POST http://localhost:5600/api/experiments HTTP/1.1
Content-Type: application/json

{
    "experiment_name": "GEMINI 2.0",
    "experiment_info": {
        "description": "GEMINI 2.0 is a new version of the GEMINI experiment"
    },
    "experiment_start_date": "2021-01-01",
    "experiment_end_date": "2021-12-31"
}

### Get Experiment Info
GET http://localhost:5600/api/experiments/GEMINI/info HTTP/1.1

### Set Experiment Info
PATCH http://localhost:5600/api/experiments/GEMINI%202.0/info HTTP/1.1
Content-Type: application/json

{
    "description": "GEMINI 2.0 is a new version of the GEMINI experiment. It is a follow-up to the original GEMINI experiment."
}

### Get Experiment Sites
GET http://localhost:5600/api/experiments/Default/sites HTTP/1.1

### Get Experiment Traits
GET http://localhost:5600/api/experiments/Default/traits HTTP/1.1

### Get Experiment Sensors
GET http://localhost:5600/api/experiments/Default/sensors HTTP/1.1

### Get Experiment Procedures
GET http://localhost:5600/api/experiments/Default/procedures HTTP/1.1

### Get Experiment Models
GET http://localhost:5600/api/experiments/Default/models HTTP/1.1

### Get Experiment Scripts
GET http://localhost:5600/api/experiments/Default/scripts HTTP/1.1

### Get Experiment Datasets
GET http://localhost:5600/api/experiments/Default/datasets HTTP/1.1

### Get Experiment Cultivars
GET http://localhost:5600/api/experiments/Default/cultivars HTTP/1.1

### Get Experiment Resources
GET http://localhost:5600/api/experiments/Default/resources HTTP/1.1


# ---------------------------------------------------------------------------
# Seasons
# ---------------------------------------------------------------------------

### Get All Seasons
GET http://localhost:5600/api/seasons HTTP/1.1

### Get All Seasons for a specific Experiment
GET http://localhost:5600/api/seasons
    ?experiment_name=GEMINI HTTP/1.1

### Get Season Info by Season Name and Experiment Name
GET http://localhost:5600/api/seasons/2021/experiment/GEMINI/info HTTP/1.1

### Set Season Info by Season Name and Experiment Name
PATCH http://localhost:5600/api/seasons/2021/experiment/GEMINI/info HTTP/1.1
Content-Type: application/json

{
    "description": "2021 is the first season of the GEMINI experiment"
}


# ---------------------------------------------------------------------------
# Sites
# ---------------------------------------------------------------------------

### Get All Sites
GET http://localhost:5600/api/sites HTTP/1.1

### Get All Sites for a specific Experiment
GET http://localhost:5600/api/sites
    ?experiment_name=Default

### Create a new Site
POST http://localhost:5600/api/sites HTTP/1.1
Content-Type: application/json

{
    "site_name": "Riverside",
    "site_city": "Riverside",
    "site_state": "California",
    "site_country": "United States",
    "site_info": {
        "description": "Riverside is a site in California"
    },
    "experiment_name": "GEMINI"
}

### Get a specific site by site name
GET http://localhost:5600/api/sites/Riverside HTTP/1.1

### Get Site Info by Site Name
GET http://localhost:5600/api/sites/Riverside/info HTTP/1.1

### Set Site Info by Site Name
PATCH http://localhost:5600/api/sites/Riverside/info HTTP/1.1
Content-Type: application/json

{
    "description": "Riverside is a site in California. It is a test site for the GEMINI experiment."
}


# ---------------------------------------------------------------------------
# Cultivars
# ---------------------------------------------------------------------------

### Get All Cultivars
GET http://localhost:5600/api/cultivars HTTP/1.1

### Create a new cultivar
POST http://localhost:5600/api/cultivars HTTP/1.1
Content-Type: application/json

{
    "cultivar_population": "Cowpea",
    "cultivar_accession": "IT97K-499-35",
    "cultivar_info": {
        "description": "IT97K-499-35 is a cowpea cultivar"
    },
    "experiment_name": "GEMINI"
}

### Get Accessions for a specific population
GET http://localhost:5600/api/cultivars/Cowpea/accessions HTTP/1.1

### Get Cultivar Info using accession and population
GET http://localhost:5600/api/cultivars/Cowpea/IT97K-499-35/info HTTP/1.1

### Set Cultivar Info using accession and population
PATCH http://localhost:5600/api/cultivars/Cowpea/IT97K-499-35/info HTTP/1.1
Content-Type: application/json

{
    "description": "IT97K-499-35 is a cowpea cultivar. It is a drought-tolerant cultivar."
}

# ---------------------------------------------------------------------------
# Traits
# ---------------------------------------------------------------------------

### Get All Traits
GET http://localhost:5600/api/traits HTTP/1.1

### Get All Traits for a specific Experiment
GET http://localhost:5600/api/traits
    ?experiment_name=Default

### Create a new Trait
POST http://localhost:5600/api/traits HTTP/1.1
Content-Type: application/json

{
    "trait_name": "Leaf Area Index",
    "trait_units": "m^2/m^2",
    "trait_level_id": 1,
    "trait_info": {
        "description": "Leaf Area Index is the ratio of leaf area to ground area"
    },
    "experiment_name": "GEMINI"
}

### Get a specific trait by trait name
GET http://localhost:5600/api/traits/Leaf%20Area%20Index HTTP/1.1

### Get Traits by Trait Level
GET http://localhost:5600/api/traits/level/1 HTTP/1.1

### Get Trait Info by Trait Name
GET http://localhost:5600/api/traits/Leaf%20Area%20Index/info HTTP/1.1

### Set Trait Info by Trait Name
PATCH http://localhost:5600/api/traits/Leaf%20Area%20Index/info HTTP/1.1
Content-Type: application/json

{
    "description": "Leaf Area Index is the ratio of leaf area to ground area. It is an important trait for measuring plant growth."
}

### Get Trait Level
GET http://localhost:5600/api/traits/Leaf%20Area%20Index/level HTTP/1.1

### Get Trait Datasets
GET http://localhost:5600/api/traits/Default/datasets HTTP/1.1

# ---------------------------------------------------------------------------
# Sensor Platforms
# ---------------------------------------------------------------------------

### Get All Sensor Platforms
GET http://localhost:5600/api/sensor_platforms HTTP/1.1

### Create a new Sensor Platform
POST http://localhost:5600/api/sensor_platforms HTTP/1.1

{
    "sensor_platform_name": "PhenoCam",
    "sensor_platform_info": {
        "description": "PhenoCam is a camera-based sensor platform"
    }
}

### Get a specific sensor platform by sensor platform name
GET http://localhost:5600/api/sensor_platforms/PhenoCam HTTP/1.1

### Get Sensor Platform Info by Sensor Platform Name
GET http://localhost:5600/api/sensor_platforms/PhenoCam/info HTTP/1.1

### Set Sensor Platform Info by Sensor Platform Name
PATCH http://localhost:5600/api/sensor_platforms/PhenoCam/info HTTP/1.1
Content-Type: application/json

{
    "description": "PhenoCam is a camera-based sensor platform. It is used for monitoring plant phenology."
}


# ---------------------------------------------------------------------------
# Sensors
# ---------------------------------------------------------------------------

### Get All Sensors
GET http://localhost:5600/api/sensors HTTP/1.1

### Get All Sensors for a specific Experiment
GET http://localhost:5600/api/sensors
    ?experiment_name=Default

### Get All Sensors for a specific platform
GET http://localhost:5600/api/sensors
    ?sensor_platform_name=Default

### Create a new Sensor
POST http://localhost:5600/api/sensors HTTP/1.1
Content-Type: application/json

{
    "sensor_name": "PhenoCamRGB",
    "sensor_platform_name": "PhenoCam",
    "sensor_info": {
        "description": "PhenoCamRGB is a camera-based sensor that captures RGB images"
    },
    "experiment_name": "GEMINI"
}

### Get a specific sensor by sensor name
GET http://localhost:5600/api/sensors/PhenoCamRGB HTTP/1.1

### Get Sensors belonging to a specific experiment
GET http://localhost:5600/api/sensors
    ?experiment_name=GEMINI

### Get Sensors belonging to a specific platform
GET http://localhost:5600/api/sensors
    ?sensor_platform_name=PhenoCam

### Get Sensor Info by Sensor Name
GET http://localhost:5600/api/sensors/PhenoCamRGB/info HTTP/1.1

### Set Sensor Info by Sensor Name
PATCH http://localhost:5600/api/sensors/PhenoCamRGB/info HTTP/1.1
Content-Type: application/json

{
    "description": "PhenoCamRGB is a camera-based sensor that captures RGB images. It is used for monitoring plant phenology."
}

# ---------------------------------------------------------------------------
# Plots
# ---------------------------------------------------------------------------

### Get All Plots
GET http://localhost:5600/api/plots HTTP/1.1

### Search Plots by Experiment Name
GET http://localhost:5600/api/plots
    ?experiment_name=Default

### Search plots by Experiment Name, Site Name, Plot Number, Plot Row and Plot Column
GET http://localhost:5600/api/plots
    ?experiment_name=Default
    &season_name=2021
    &site_name=Default
    &plot_number=1
    &plot_row_number=1
    &plot_column_number=1

### Get Plot by experiment, season and site
GET http://localhost:5600/api/plots/experiment/Default/season/2021/site/Default HTTP/1.1

### Get Plots by Cultivar Accession and Population
GET http://localhost:5600/api/plots/cultivar/Default/Default HTTP/1.1

### Create a new Plot
POST http://localhost:5600/api/plots HTTP/1.1
Content-Type: application/json

{
    "plot_number": 1,
    "plot_row_number": 1,
    "plot_column_number": 1,
    "plot_info": {
        "description": "Plot 1 is a test plot"
    },
    "plot_geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [0, 0],
                [0, 1],
                [1, 1],
                [1, 0],
                [0, 0]
            ]
        ]
    },
    "experiment_name": "GEMINI",
    "season_name": "2021",
    "site_name": "Riverside",
    "cultivar_accession": "Default",
    "cultivar_population": "Default"
}

# ---------------------------------------------------------------------------
# Sensor Records
# ---------------------------------------------------------------------------

### Get All Sensor Records
### Check example_sensor_data.py 
GET http://localhost:5600/api/sensor_records
    ?sensor_name=Campbell%20CR1000
    &collection_date=2023-09-05
    
### Filter Sensor Records by Sensor Name and collection date
GET http://localhost:5600/api/sensor_records
    ?sensor_name=Weather%20Sensor


### Filter Sensor Records by Sensor Name, collection date, experiment and site
GET http://localhost:5600/api/sensor_records
    ?sensor_name=Weather%20Sensor
    &site_name=Davis
    &season_name=2021