@baseUrl = http://localhost:8000/

#### API Base Requests

GET {{baseUrl}}

#### Cultivar Requests

### Get all cultivars
GET {{baseUrl}}api/cultivars

### Create a new cultivar
POST {{baseUrl}}api/cultivars
Content-Type: application/json

{
  "cultivar_population": "Test Population",
  "cultivar_accession": "Test Accession",
  "cultivar_info": {"testKey": "testValue"},
  "experiment_name": "Experiment A"
}

### Get a cultivar by ID
GET {{baseUrl}}api/cultivars/{{response.body.id}}


